import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { Sidebar } from '@/components/Sidebar'
import { Header } from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-100`}>
        <div className="grid h-screen w-screen grid-cols-[200px_auto]">
          <Sidebar />

          <div>
            <Header />

            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
